# Default properties

spring:
  # Write timestamps in ISO format
  jackson.serialization.write-dates-as-timestamps: false

  application:
    name: @project.name@

logging.level:
  org.springframework: INFO
  dk.fnie.wolt: DEBUG
